dist: trusty
git:
  depth: 5 # use depth 5 to leave enough room for concurrent builds
language: ruby
# always specify exact versions so we know which version we are testing
rvm:
- &release_ruby 2.7.2
- 2.6.6
- 2.5.8
- 2.4.10
- &oldest_ruby 2.3.8
matrix:
  include:
  - rvm: jruby-9.2.10.0
    env: JRUBY_OPTS='--dev'
  - rvm: jruby-9.1.17.0
    env: JRUBY_OPTS='--dev'
  - rvm: *oldest_ruby
    env: ROUGE_VERSION='~> 2.0.0'
  - rvm: truffleruby-20.2.0
    # run against TruffleRuby nightly or if TruffleRuby is mentioned in commit message
    if: type = cron OR commit_message =~ /TruffleRuby/ OR commit_message =~ /truffleruby/
env:
  global:
  # use system libraries to speed up installation of nokogiri
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - PYGMENTS_VERSION='~> 1.2.0'
  - SOURCE_DATE_EPOCH=1521504000
script: bundle exec rake coverage test:all
after_success: bundle exec rake build:dependents
#notifications:
#  email: false
#  irc: 'irc.freenode.org#asciidoctor'
deploy:
  provider: rubygems
  gem: asciidoctor
  api_key: ${RUBYGEMS_API_KEY}
  on:
    tags: true
    repo: asciidoctor/asciidoctor
    rvm: *release_ruby
